export const IA_CONSTANTS = {
    PARAMS_GROUP: {
        IA_INSPECTION_WORK: "IA_INSPECTION_WORK",
        IA_UTILITY_BILL_TYPE: "IA_UTILITY_BILL_TYPE",
        IA_UTILITY_BILL_REASON: "IA_UTILITY_BILL_REASON",
    }
}